### ISSUE TITLE
clearer instructions on how to exactly update plug in

### ISSUE THREAD

**Issue by mekias123** [qiceradar/qiceradar#33]
I believe this issue was fixed when you updated plug in on QGIS and made sure I was using the correct new data. But I think maybe  more clear instructions would be helpful for future use 

<img width="1353" alt="Screenshot 2024-07-08 at 1 10 27 PM" src="https://github.com/qiceradar/qiceradar_plugin/assets/59778107/b935f6f0-1e3c-4b2e-b061-334943e487f4">

**Comment by lauralindzey** [comment]
Hi @mekias123 -- is this an old screenshot, or are you having this issue again right now?

**Comment by mekias123** [comment]
Not an issue anymore, but I thought from the last meeting you asked me to post this error in the github issues section for future reference.

**Comment by lauralindzey** [comment]
OK, thank you!

And yes, posting issues on github is the right place for them -- it's easier for me to track them here than on Zulip, and I can directly link code changes to the issue that they're addressing.

For my own reference: I'm not sure what mistake was made in the original update; either didn't pull the newest version of the code, or hadn't imported an up-to-date gpkg file.

**Comment by lauralindzey** [comment]
I've attempted to update the README in !c4b3f13 for the mechanics of updating the plugin.

There are also two categories of code changes that will help with this:
1) Automatically detect that the index was deleted then re-added (as happens when it is updated), and re-run the spatial index. Fixed: 8d94c44
2) Detect that there's an index/code version mismatch. (Not currently an issue; should add + test this logic the next time I introduce a breaking change in the index.

So, closing for now since I've addressed what I can.
