### ISSUE TITLE
Problem to install the plugin for QIceRadar

### ISSUE THREAD

**Issue by marie-axelle-ut** [qiceradar/qiceradar#68]
Hello,

I’m trying to download Qiceradar, but at the step where I need to install the plugin, QGIS doesn’t find anything to install in the ZIP file. I’ve attached a screenshot for reference (sorry it is in French, I could not find how to put QGIS in English).

![Capture d’écran 2024-09-18 à 2 25 45 PM](https://github.com/user-attachments/assets/f630e012-1d08-405b-9e07-f71f98595735)

**Comment by lauralindzey** [comment]
Hi! Thanks for the screenshot -- that helps a lot.

It looks like you may have extracted the zip file before trying to install the plugin. You need to find qiceradar-main.zip, and select that file. (You may need to re-download it.)

**Comment by lauralindzey** [comment]
@marie-axelle-ut -- let me know if that works? If not, send me an email (qiceradar@gmail.com) and we can hop on a quick Zoom.

**Comment by marie-axelle-ut** [comment]
It did not work, I sent you an email.

**Comment by lauralindzey** [comment]
Lovely to meet you @marie-axelle-ut, and please let me know if you have any other problems or questions!

From our call: it turns out the issue was that Safari was set to auto-extract the zip file after downloading; we disabled this behavior and then the normal install steps worked.
* Safari -> "Settings..."
* Select "General"
* At the bottom, uncheck "Open safe files after downloading"

Notably, trying to re-compress the auto-extracted qiceradar-main directory did not work. That yielded the below error:
<img width="944" alt="Screenshot 2024-09-18 at 12 57 59" src="https://github.com/user-attachments/assets/e3e3e533-bd4a-4645-94ce-5644dc0f841d">
